cloudhub:
  env_id: "0b12e2ae-f34d-4e20-93fa-3057a417ade4"
  client_id: "79314592f7cb4944bb059af6dda16e29"
  # Por seguridad, se informa por variable de entorno
  client_secret: ""
  
sharepoint-tcct:
  urlToken: ""
  client_id: ""
  # Por seguridad, se informa por variable de entorno
  client_secret: ""
  scope: "https://graph.microsoft.com/.default openid"
  nameSite: ""
  nameDrive: ""
